# Generated by Django 3.0.4 on 2020-03-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhdb', '0002_baseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('create_time', models.IntegerField()),
                ('img_url', models.CharField(max_length=255)),
                ('n_type', models.CharField(max_length=1)),
            ],
        ),
    ]
