# Generated by Django 3.0.4 on 2020-03-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhdb', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_show',
            field=models.CharField(max_length=1, null=True, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
