# Generated by Django 3.0.4 on 2020-03-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhdb', '0005_auto_20200318_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='create_time',
            field=models.IntegerField(null=True),
        ),
    ]
