# Generated by Django 3.0.4 on 2020-03-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhdb', '0007_job_valid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_show',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_age',
            field=models.CharField(max_length=20),
        ),
    ]
