# Generated by Django 3.0.4 on 2020-03-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhdb', '0008_auto_20200318_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='update_time',
            field=models.IntegerField(null=True),
        ),
    ]
