# Generated by Django 3.0.4 on 2020-03-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhdb', '0009_job_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitudes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.IntegerField()),
            ],
        ),
    ]
