# Generated by Django 3.0.4 on 2020-03-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhdb', '0010_aptitudes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urls', models.CharField(max_length=255)),
                ('create_time', models.IntegerField()),
            ],
        ),
    ]
