# Generated by Django 3.0.4 on 2020-03-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhdb', '0011_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
