# Generated by Django 3.0.4 on 2020-03-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhdb', '0013_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_del',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
