# Generated by Django 3.0.4 on 2020-03-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhdb', '0014_news_is_del'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='banner_id',
            new_name='aptitudes_id',
        ),
    ]
